name: spacerent_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-134.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.7
  flutter: 
    sdk: flutter
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/img/

